title: tonns
description: >-
  Work Efficient - With the Community - Be Smart, Social, Green
baseurl: ""
url: "https://tonns.app"
company: tonns GmbH
street: Badstraße 13-15
city: 90762 Fürth
hrb: HRB 21752
court: folgt
director: Markus Römer
email: founder@tonns.app
phone: 0911 47883546
show_price: false

collections:
  authors:
    title: Authors
    output: true
    permalink: "/about/:title.html"
  posts:
    title: Posts
    output: true
    permalink: /:year/:month/:day/:title:output_ext
  features:
    title: Features
    output: false
  streets:
    title: Streets
    output: true
    permalink: /streets/:title
  cities:
    title: Cities
    output: true
    permalink: /cities/:title
cloudflare_image_base: "/cdn-cgi/image/format=webp"
include:
  - ".well-known"
exclude:
  - "jekyll_runner"
  - "functions_firebase"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
